server:
  port: 1111
  servlet:
    contextPath: /produce
spring:
  config:
    import: classpath:error-message.yml
  
kafka:
  bootstrap-servers: 192.168.50.119:9092
  wikimedia-topic: wikimedia.recentchange
    